### PR TITLE
Fixing ReadComicOnlineLi

### PR DESCRIPTION
**Pull request by xOnlyFadi**
I changed the bypass user-agent to a desktop user-agent that makes the page become a desktop page and updated selectors for search and viewmore to make them work with no problems

### CODE REVIEW

**Comment by TheNetsky** [comment]
Have you tested any of these and have a test repo?

Since I did all of these changes on my local devices as well, yet still had issues with the CloudFlare bypass.

**Comment by xOnlyFadi** [comment]
I have tested them on my local network and they are working with no problems

**Comment by TheNetsky** [comment]
Seems like even my solution is working right now, however they changed the way images are loaded within the site, the comic pages. So if you manage to uncypher that as well, that would be great.

**Comment by xOnlyFadi** [comment]
the thing is in readcomiconline.li cloudflare protection is if the user-agent is different you can't scrape the site but if it's the same user-agent for bypassing and reuqests it will work with no problems at all

**Comment by TheNetsky** [comment]
> the thing is in readcomiconline.li cloudflare protection is if the user-agent is different you can't scrape the site but if it's the same user-agent for bypassing and reuqests it will work with no problems at all

Not what I meant, everything works fine except the comic pages, which can no longer be parsed using my original method and are now (from my quick look) hidden behind some JS script.

**Comment by xOnlyFadi** [comment]
> > the thing is in readcomiconline.li cloudflare protection is if the user-agent is different you can't scrape the site but if it's the same user-agent for bypassing and reuqests it will work with no problems at all
> 
> Not what I meant, everything works fine except the comic pages, which can no longer be parsed using my original method and are now (from my quick look) hidden behind some JS script.

I have a method to parse the JS script i can give you the code

**Comment by TheNetsky** [comment]
I'm not planning to work on sources for a while, if you can manage to make it work, add it to this PR and make a test repo.

**Comment by xOnlyFadi** [comment]
Ok no problem should i use my method to get htm response or your method?

**Comment by TheNetsky** [comment]
Whatever works :)

**Comment by xOnlyFadi** [comment]
I fixed everything that had a problem the only thing now is pages 
[Imgur video](https://imgur.com/a/2nisS5a)

**Comment by TheNetsky** [comment]
> I fixed everything that had a problem the only thing now is pages [Imgur video](https://imgur.com/a/2nisS5a)

I know, that's what I've been saying.

Everything is working on my local build as well, all except for pages.
I already had fixed everything you've done in this PR, however in the past the CF was more strict than it is now.

**Comment by xOnlyFadi** [comment]
just finished working on the new method that parse the the pages for readcomiconline here is my [test repo ](https://xonlyfadi.github.io/netskys-extensions/0.6/)
image

**Comment by xOnlyFadi** [comment]
They just changed the algorithm for the scrambled url pages

**Comment by vetleledaal** [comment]
> They just changed the algorithm for the scrambled url pages

Not familiar with ts, but you can use something like this for version 1.1:
```js
function beau(lstImages) {
    return lstImages.map(url => {
        if (url.startsWith('https')) {
            return url;
        }

        const containsS0 = url.includes('=s0');
        url = url.slice(0, containsS0 ? -3 : -6);
        url = url.slice(4, 22) + url.slice(25);  
        url = url.slice(0, -6) + url.slice(-2);
        url = atob(url);
        url = url.slice(0, 13) + url.slice(17);
        url = url.slice(0, -2) + (containsS0 ? '=s0' : '=s1600');

        return 'https://2.bp.blogspot.com/' + url;
    });
}
```

Or if you want to clean it up yourself, here's more or less the original code lightly deobfuscated:
```js
function beau(lstImages) {
    for (var i = 0; i < lstImages.length; i++) {
        if (lstImages[i].indexOf('https') != 0) {
            var W = lstImages[i];
            W.indexOf('=s0') > 0 ? W = W.substring(0, W.length - 3) : W = W.substring(0, W.length - 6),
            W = W.substring(4, 22) + W.substring(25),
            W = W.substring(0, W.length - 6) + W[W.length - 2] + W[W.length - 1],
            W = atob(W),
            W = W.substring(0, 13) + W.substring(17),
            lstImages[i].indexOf('=s0') > 0 ? W = W.substring(0, W.length - 2) + '=s0' : W = W.substring(0, W.length - 2) + '=s1600',
            lstImages[i] = 'https://2.bp.blogspot.com/' + W;
        }
    }
}
```

**Comment by TheNetsky** [comment]
@vetleledaal @xOnlyFadi 

If you guys want to keep monitoring the site, feel free. However personally I am not going to waste my time on this if they keep changing their scrambling. Feel free to open another PR with a permanent solution since the current one doesn't work anymore? At least that's what I am reading here.

I thank you both for your efforts, feel free to keep me updated. :)

**Pull request closed without merging**
