### PR TITLE
McReader | Regex chapter names like 1-5 too

### PR DESCRIPTION
**Pull request by niclimcy**
Convert 1-5 to 1.5 before adding to index

### CODE REVIEW

**Comment by niclimcy** [comment]
Not sure if they will come up with 56-5-5 because 56.5.5 is definitely not a number LOL
photo_2023-04-04_20-57-22

**Comment by niclimcy** [comment]
wait regex can be further improved do not merge

**Comment by TheNetsky** [comment]
You finished?

**Comment by niclimcy** [comment]
Yes

**Pull request merged**
